a = 12
b = 10

if a > b:
    print('Variabel a lebih besar dari variabel b')
    
a = 12
b = 12
if a > b:
    print('Variabel a lebih besar dari variabel b')
if a < b:
    print('Variabel a lebih kecil dari variabel b')
if a == b:
    print('Variabel a sama dengan variabel b')

a = 7

if (a % 2) == 0:
    print('Variabel a berisi angka genap')
if (a % 2) != 0:
    print('Variabel a berisi angka ganjil')
