# TIPE DATA #
# Tipe Data String
web = "Belajar Python di STIKOM Banyuwangi"
print(web)
#Tipe Data Integer
web = 1500
print(web)
#Tipe Data Float
web = 99.123
print(web)
#Tipe Data Complex Number
web = 4j
print(web)
#Tipe Data Boolean
web = True
print(web)
#Tipe Data List
web = ["satu", "dua", "tiga", "satu"]
print(web)
#Tipe Data Tuple
web = ("satu", "dua", "tiga", "satu")
print = (web)
#Tipe Data Set
web = {"satu", "dua", "tiga", "empat"}
print(web)
#Tipe Data Dictionary
web = {"satu":1, "dua":2, "tiga":"a", "empat":True}
print(web)
